[General]
VLGDeviceKey=1780985397310|1781264556110|1781342798879|1781430562999
QingIpcVersion=1.0.0.6
libpath=/nix/store/z1qsflvkvg0cmm8yg3vp8lifyxmj6yy6-wpsoffice-cn-12.1.2.25882/opt/kingsoft/wps-office/office6/addons/qing
newshare2=false
uploadFile=false
shareFile=false
DesktopSync=false
SpecifyFolderSync=false
specific_companyintro=true
qingVersion=1
RealTimeUploadSwitchFlag=
OverSpaceUploadEnable=false
SendBy=false
UploadSync=false
crash=1
diffUserIdentify=false
fileTransfer=false
guestAccount=false
kicDesktopSyncSwitch=false
kicFileTransferSwitch=false
kicSendBySwitch=false
kicShareFileSwitch=false
kicSyncFolderSwitch=false
kicUploadFileSwitch=false
kicUploadSyncSwitch=false
pluginfeaturetag="oldCacheUsing=12.1.2.25882&supportcmdopen=12.1.2.25882&supportroamingpush=12.1.2.25882"

[usercenter]
overFileSizeUpload_yunkit=true
funcRegSw\useSyncAssist=1
funcRegSw\useSyncAssistV2=1
all\wpsbox\AllDocRadar_Ignore=0
all\wpsbox\MarkShareMsgNewRemind=1
devices\softbuss_file_label=true
funcRegSw\isSupportPluginFilesActionEx=false
welcomeBind=false
all\wpsbox\Dispersed_AllDocRadar_Ignore=1
devices\label_sync_page=true
all\wpsbox\Radar_Ignore\qqtim=1
all\wpsbox\Radar_Ignore\wechat=1
all\wpsbox\Radar_Ignore\webdownload=1
all\wpsbox\Radar_Ignore\desktop=1

[userinfo]
forceLoginState=false
companyid=
userid=

[Nse]
IsEnterprise=1

[backup]
DesktopSync=true
SendBy=true
SpecifyFolderSync=true
UploadSync=true
fileTransfer=true
shareFile=true
uploadFile=true

[clouddisk]
batchRemove=1
supportPMoveFolder=1

[msgcenter]
MsgCenterMsgVersion=13

[netswitch]
en_US\12.1.2_12.1.2.25882_00001.00000001=eyJRUHVzaCI6InRydWUiLCJjcnlwdGNvb2tpZSI6InRydWUiLCJtb2JpbGVQdXNoIjoiZmFsc2UiLCJxaW5pdSI6Im9wZW4iLCJyZXN1bHQiOiJvayIsInJvYW1Ib21lcGFnZVNldHRpbmdHdWlkIjoidHJ1ZSIsInNob3dndWlkZSI6ImZhbHNlIiwidXBkYXRlVGlwSW50ZXJ2YWwiOiIzNjAwMCJ9
zh_CN\12.1.2_12.1.2.25882_00001.00000001=eyJRUHVzaCI6InRydWUiLCJjcnlwdGNvb2tpZSI6InRydWUiLCJtb2JpbGVQdXNoIjoiZmFsc2UiLCJxaW5pdSI6Im9wZW4iLCJyZXN1bHQiOiJvayIsInJvYW1Ib21lcGFnZVNldHRpbmdHdWlkIjoidHJ1ZSIsInNob3dndWlkZSI6ImZhbHNlIiwidXBkYXRlVGlwSW50ZXJ2YWwiOiIzNjAwMCJ9

[limitGuide]
localFileSyncBtn=false
syncBtnGuideSwitch=false
tabCloseGuide=TurnOff
