#!/run/current-system/sw/bin/bash

wall_path="$HOME/Pictures/background/"

while true; do
  find "$wall_path" -type f | shuf | while read -r file; do 
    if [[ -f $file ]]; then
      file_name=$(basename "$file")
      feh --bg-fill $file
      sleep 30
    fi
  done
done
